name: Cypress Tests

on:
  issue_comment:
    types: [created, edited]

jobs:
  cypress-tests:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/e2e') }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install backend dependencies
        run: |
          cd ./backend
          npm install --frozen-lockfile
      - name: Start backend
        run: |
          cd ./backend
          node app.js &

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: ./frontend
          start: node app.js &
          wait-on: 'http://localhost:4000, http://localhost:4001, '
